perl-Crypt-OpenSSL-Bignum
perl-Encode-Detect
perl-IP-Country
perl-Image-Info
perl-Net-Ident
perl-Crypt-OpenSSL-Random
perl-Crypt-OpenSSL-RSA
perl-TimeDate
perl-MailTools
perl-Mail-DKIM
perl-Net-DNS-Resolver-Programmable
perl-NetAddr-IP
perl-Mail-SPF
re2c
pysetuptools
perl-www-robotrules
perl-http-date
perl-file-listing
perl-IO-HTML
perl-encode-locale
perl-lwp-mediatypes
perl-html-tagset
perl-html-parser
perl-http-message
perl-http-negotiate
perl-http-cookies
perl-http-daemon
perl-net-http
perl-Geo-IP
perl-IO-Socket-IP
libwww-perl
spamassassin
